### ISSUE TITLE
403 Forbidden (OpenURI::HTTPError) Error

### ISSUE THREAD

**Issue by brettchalupa** [beerlington/thundersnow#1]
While using thundersnow to get the weather where I live, `thundersnow 05401` I get an `open_http` error.

```
/Users/brettchalupa/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/open-uri.rb:346:in `open_http': 403 Forbidden (OpenURI::HTTPError)
```

Any solution for this issue?

**Comment by beerlington** [comment]
This probably has something to do with it http://thenextweb.com/google/2012/08/28/did-google-just-quietly-kill-private-weather-api/

I never use it, but it would probably be easy to update to use another weather API

**Comment by brettchalupa** [comment]
That would make sense. I'll go ahead and fork this to switch it out to another weather API. :snowflake:

**Comment by beerlington** [comment]
cool, feel free to change the internals around if you need to. I sort of just hacked it together with minimal tests.
